# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-28 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('name', models.CharField(max_length=256)),
                ('subdomain', models.CharField(max_length=32, unique=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('location', models.CharField(max_length=256)),
                ('sent_mail', models.EmailField(blank=True, max_length=70, null=True)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('timezone', models.CharField(blank=True, max_length=32, null=True)),
                ('first_step_info', models.TextField(blank=True, max_length=20000, null=True)),
                ('participant_fields', jsonfield.fields.JSONField(blank=True, default='["name", "surname"]', null=True)),
                ('participant_reqired_fields', jsonfield.fields.JSONField(blank=True, default='["name", "surname"]', null=True)),
                ('companion_fields', jsonfield.fields.JSONField(blank=True, null=True)),
                ('companion_reqired_fields', jsonfield.fields.JSONField(blank=True, null=True)),
                ('payment_text', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_sent_mail_upn', models.TextField(blank=True, max_length=5000, null=True)),
                ('payment_sent_mail_paypal', models.TextField(blank=True, max_length=5000, null=True)),
                ('promotion_code', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='media_cdn/logo/')),
                ('public_logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='media_cdn/public_logo/')),
                ('token', models.CharField(max_length=100)),
                ('api_username', models.CharField(blank=True, max_length=32, null=True)),
                ('api_key', models.CharField(blank=True, max_length=32, null=True)),
                ('calculated', models.BooleanField(default=False)),
                ('registration_step_finished', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('name', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=256, null=True)),
                ('lecture_room', models.CharField(blank=True, max_length=256, null=True, verbose_name='Lecture room')),
                ('bar_tracking', models.BooleanField(default=False)),
                ('device_entrance_position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=1, verbose_name='UHF Device position')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('ticket_name', models.CharField(blank=True, max_length=512, null=True)),
                ('days', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Event.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('track_is_payable', models.BooleanField(default=False, verbose_name='is payable')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPayPal',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Event.Payment')),
                ('paypal_enabled', models.BooleanField(default=False)),
                ('client_id', models.CharField(blank=True, max_length=512, null=True)),
                ('client_key', models.CharField(blank=True, max_length=512, null=True)),
                ('mode', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Event.payment',),
        ),
        migrations.CreateModel(
            name='PaymentUPN',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Event.Payment')),
                ('upn_enabled', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('account_number', models.CharField(blank=True, max_length=512, null=True)),
                ('bic', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Event.payment',),
        ),
        migrations.AddField(
            model_name='paymentticket',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='Event.Track'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Event.Event'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='track',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.Track'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
