# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-19 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='access_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='uhf_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
