# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20170919_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='card_designer',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
