# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-06 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20170930_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='device_entrance_position2',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=1, verbose_name='UHF Device ID 2 position'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='device_id2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='device_entrance_position',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=1, verbose_name='UHF Device ID 1 position'),
        ),
    ]
