# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20171006_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentticket',
            name='payable',
            field=models.BooleanField(default=False),
        ),
    ]
