# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_paymentticket_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentticket',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
