
"""
Django settings for Ideconference project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import paypalrestsdk

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1&c@ng-5pwom-p231^##-f@0xuo5xi4th0^2$+b=^q8#5oy*qn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['myapp.com']

AUTH_USER_MODEL = 'Landing.User'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Event',
    'Visitor',
    'Landing',
    'api',
    'bootstrap3',
    'django_countries',
    'django_summernote',
    'widget_tweaks',
    'bootstrap3_datetime',
    'djangoformsetjs',
    'social_django',
    'snowpenguin.django.recaptcha2',
    'wkhtmltopdf',
    'mail_templated',
    'import_export',
)

MIDDLEWARE_CLASSES = (
    'Ideconference.middleware.subdomain_middleware.SubdomainMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
)

ROOT_URLCONF = 'Ideconference.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
)

WSGI_APPLICATION = 'Ideconference.wsgi.application'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static_manual"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static")


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media_cdn")


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db/db2.sqlite'),
    #},
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'conference',
        'USER': 'root',
        'PASSWORD': 'r00tPasswd123',
        'HOST': 'db',
        'PORT': 3306,
    },
    'api': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db/apidb2.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'sl-si'

TIME_ZONE = 'Europe/Ljubljana'
#TIME_ZONE ='Asia/Kolkata'
USE_I18N = True

USE_L10N = False

USE_TZ = True

BIRTH_YEAR_FORMAT = 'DD. MM. YYYY'

#DATETIME_FORMATS = ['%d-%m-%Y %H:%M','%m/%d/%Y %H:%M']
# DATETIME_FORMAT = '%m/%d/%Y %H:%M'
# DATETIME_FORMATS = ['%d-%m-%Y %H:%M', '%m/%d/%Y %H:%M']

DATETIME_INPUT_FORMATS = [
    '%d. %m. %Y',
    '%d.%m.%Y %H:%M:%S',
    '%d.%m.%Y %H:%M',
    '%d. %m. %Y %H:%M:%S',
    '%d. %m. %Y %H:%M',
    '%d.%m.%Y %H:%M:%S.%f',
    '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M:%S.%f',  # '2006-10-25 14:30:59.000200'
    '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
    '%Y-%m-%d',              # '2006-10-25'
    '%m/%d/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
    '%m/%d/%Y %H:%M:%S.%f',  # '10/25/2006 14:30:59.000200'
    '%m/%d/%Y %H:%M',        # '10/25/2006 14:30'
    '%m/%d/%Y %I:%M %p',        # '10/25/2006 2:30 pm'
    '%m/%d/%Y',              # '10/25/2006'
    '%m/%d/%y %H:%M:%S',     # '10/25/06 14:30:59'
    '%m/%d/%y %H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
    '%m/%d/%y %H:%M',        # '10/25/06 14:30'
    '%m/%d/%y',              # '10/25/06'
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

EVENTS_ON_LANDING = 12

SUMMERNOTE_CONFIG = {
    # Customize toolbar buttons
    'toolbar': [
        ['style', ['style']],
        ['font', ['bold', 'italic', 'underline', 'clear']],
        #['fontname', ['fontname']], # probably best to have uniform fonts
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['height', ['height']],
        # ['table', ['table']],
        # ['insert', [ 'hr']], # picture removed
        # ['view', ['fullscreen', 'codeview']],
        # ['help', ['help']]
    ],
    'internal_css': (
        '../static/django_summernote/summernote.css'
    ),

}

VISITOR_FIELD_CLASS = {
    'personal': ['name', 'surname', 'email', 'company_name','company','gender', 'address', 'city', 'post',
                  'country', 'birth_year'],
    'company': ['company_address','company_invoice',
                'company_email','tax_number'],
    'event': ['status','nutrition', 'dinner', 'network_visible','days_on_event']
}

EMAIL_DOMAIN = "@idconferencaj.me"

GOOGLE_MAPS_API_KEY = "AIzaSyBdBR6GCoGFmDbvI7hAaCJBtZXDBK6g-vc"
GOOGLE_MAPS_TZ_API_KEY = "AIzaSyDQnc1oaOAjONgSmQjTS6M0QN1YgL8pyIo"

SOCIAL_AUTHLOGIN_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = '/event/list/'

SOCIAL_AUTH_FACEBOOK_KEY = '1890261084628966'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '47c14519ec6258dc2c4241c5964e93ef'  # App Secret
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email'
}

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '278129643455-laosl68tpg1idma1kq0mdqlu9irqrdhq.apps.googleusercontent.com'  # App ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'MruLpdzXkV8hoOi-61LU8laz'  # App Secret

RECAPTCHA_PRIVATE_KEY = '6LdsfC4UAAAAACLo1hVSbftK3gYHerH9c_qtskTf'
RECAPTCHA_PUBLIC_KEY = '6LdsfC4UAAAAAGxxZJShutZ8Gt2tP_mID6W2sS7A'


WKHTMLTOPDF_CMD_OPTIONS = {
    'quiet': True,
}

#e-mail settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = False
EMAIL_HOST = 'mail.fix.si'
EMAIL_PORT = 2525
EMAIL_HOST_USER = 'info@idconference.eu'
EMAIL_HOST_PASSWORD = 'IDConference112358:'
