# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-28 16:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('surname', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Female')], max_length=1, null=True)),
                ('birth_year', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('post', models.CharField(blank=True, max_length=256, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('nutrition', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('company_invoice', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('company_address', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_number', models.IntegerField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=256, null=True)),
                ('network_visible', models.BooleanField(default=False)),
                ('for_pay', models.FloatField(default=0)),
                ('payed', models.BooleanField(default=False)),
                ('is_upn', models.BooleanField(default=False)),
                ('pay_details', models.TextField(blank=True, max_length=2048, null=True)),
                ('upn_reference', models.IntegerField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_companion', models.BooleanField(default=False)),
                ('days_on_event', models.IntegerField(blank=True, default=0, null=True)),
                ('idnumber', models.IntegerField(default=0)),
                ('soft', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('uhf_id', models.CharField(blank=True, max_length=128, null=True)),
                ('barcode_no', models.CharField(blank=True, max_length=128, null=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('registration_step_finished', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='Event.Event')),
                ('lectures', models.ManyToManyField(to='Event.Lecture')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Female')], max_length=1, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2015), django.core.validators.MinValueValidator(1920)])),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('post', models.CharField(blank=True, max_length=256, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
