# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-19 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='nfc_id',
            field=models.CharField(blank=True, default=0, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eventprofile',
            name='updated_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='eventprofile',
            name='uhf_id',
            field=models.CharField(blank=True, default=0, max_length=128, null=True),
        ),
    ]
