# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0002_auto_20170919_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='birth_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
