# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0004_eventprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
    ]
